###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = ghostty
$fileManager = nautilus
$launcherMenu = walker
$display_manager = python3 ~/.config/hypr/scripts/display_manager.py
$smart_workspace = python3 ~/.config/hypr/scripts/smart_workspace.py
$powerMenu = python3 ~/.config/hypr/scripts/powermenu.py