# This is an example Hyprland config file.
# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/

# Please note not all available settings / options are set here.
# For a full list, see the wiki

# You can split this configuration into multiple files
# Create your files separately and then link them to this file like this:
# source = ~/.config/hypr/myColors.conf

# Programs
source = ~/.config/hypr/confs/programs.conf

# Monitors
source = ~/.config/hypr/confs/monitors.conf

# Autostart
source = ~/.config/hypr/confs/autostart.conf

# Environment variables
source = ~/.config/hypr/confs/env.conf

# Theme
source = ~/.config/hypr/confs/theme.conf

# Input
source = ~/.config/hypr/confs/input.conf

# Keybinds
source = ~/.config/hypr/confs/keybinds.conf

# Window rules
source = ~/.config/hypr/confs/windowrules.conf
